import type { Metadata } from 'next';
import './globals.css';
import Nav from '@/components/Nav';
import { UserProvider } from '@/providers/UserProvider';
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body>
        <UserProvider>
          <Nav></Nav>
          <div className='p-4!'>{children}</div>
        </UserProvider>
      </body>
    </html>
  );
}
